AWSTemplateFormatVersion: '2010-09-09'
Description: Serverless Secret Keeper – Analytics & Summary Stack
Parameters:
  EnvironmentName:
    Type: String
    Default: prod
  LambdaS3Bucket:
    Type: String
    Description: S3 bucket containing zipped Lambda code
  LambdaSummaryKey:
    Type: String
    Description: S3 key for daily_summary.zip
  TableName:
    Type: String
    Description: DynamoDB table name from Core stack
  Region:
    Type: String
    Default: us-west-2

Resources:
  SecretKeeperTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "SecretKeeperSummary-${EnvironmentName}"

  EmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      Endpoint: "<YOUR_EMAIL>"
      TopicArn: !Ref SecretKeeperTopic

  SmsSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sms
      Endpoint: "<YOUR_PHONE>"
      TopicArn: !Ref SecretKeeperTopic

  SummaryRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: { Service: lambda.amazonaws.com }
            Action: sts:AssumeRole
      Policies:
        - PolicyName: DailySummaryPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:Scan
                  - dynamodb:DescribeTable
                Resource: !Sub "arn:aws:dynamodb:${Region}:${AWS::AccountId}:table/${TableName}"
              - Effect: Allow
                Action: sns:Publish
                Resource: !Ref SecretKeeperTopic
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  DailySummaryFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "SecretKeeperSummary-${EnvironmentName}"
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Role: !GetAtt SummaryRole.Arn
      Code:
        S3Bucket: !Ref LambdaS3Bucket
        S3Key: !Ref LambdaSummaryKey
      Timeout: 30
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
          SNS_TOPIC_ARN: !Ref SecretKeeperTopic

  DailyTriggerRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Trigger summary Lambda once per day
      ScheduleExpression: cron(0 18 * * ? *)
      State: ENABLED
      Targets:
        - Arn: !GetAtt DailySummaryFunction.Arn
          Id: "TargetFunctionV1"

  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DailySummaryFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt DailyTriggerRule.Arn

  Dashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub "SecretKeeperDashboard-${EnvironmentName}"
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "x": 0,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "ServerlessSecretKeeper", "SecretsCreated" ],
                  [ ".", "SecretsDeleted" ]
                ],
                "period": 300,
                "stat": "Sum",
                "region": "${Region}",
                "title": "Secrets Created vs Deleted"
              }
            },
            {
              "type": "text",
              "x": 0,
              "y": 6,
              "width": 12,
              "height": 3,
              "properties": {
                "markdown": "### Serverless Secret Keeper Metrics\nMonitor secret activity, deletions, and average TTL."
              }
            }
          ]
        }

  # Optional QuickSight permissions (no error if QuickSight disabled)
  QuickSightAccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: quicksight.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: QuickSightDynamoAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:DescribeTable
                  - dynamodb:Scan
                Resource: !Sub "arn:aws:dynamodb:${Region}:${AWS::AccountId}:table/${TableName}"

Outputs:
  TopicArn:
    Value: !Ref SecretKeeperTopic
  DashboardName:
    Value: !Ref Dashboard
